### ISSUE TITLE
critical security issue

### ISSUE THREAD

**Issue by shabane** [zankoAn/FDB#2]
hi my friend, in the setting.py of your blog is the **security password** leaked.
in line 24.

@zankoAn

**Comment by zankoAn** [comment]
I'm a beginner in Django and trying to be better, I appreciate your help and I fixed a bug by changing this line (if you want to use defualt secret_key):

SECRET_KEY = environ.get ("DJANGO_SECRET_KEY", "DEFAULT_KEY")

And for the custom secret key can create an .env file and add it to .gitignore

Are these enough?

**Comment by shabane** [comment]
its a good idea, and im a junior django developer too (:

**Comment by zankoAn** [comment]
Thanks and I wish you luck 🌸

**Comment by zankoAn** [comment]
> its a good idea, and im a junior django developer too (:

Thanks and I wish you luck 🌸
